services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  webignition\SymfonyEncapsulatingRequestResolver\Services\Resolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }
