name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    name: PHPUnit tests - PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
        symfony: ['5.4.*', '6.0.*']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet

      - name: Install symfony/*  ${{ matrix.symfony }}
        uses: php-actions/composer@v6
        with:
          command: require symfony/config ${{ matrix.symfony }} symfony/dependency-injection ${{ matrix.symfony }} symfony/http-kernel ${{ matrix.symfony }} symfony/yaml ${{ matrix.symfony }} -W

      - name: Run tests
        run: composer test
