name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    name: PHPUnit tests - PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
        symfony: ['5.4.*', '6.0.*']
        include:
          - symfony: 5.4.*
            composer-flags: --prefer-lowest

          - symfony: 6.0.*
            composer-flags: --prefer-stable

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          command: update
          args: --ignore-platform-reqs ${{ matrix.composer-flags }}

      - name: Run tests
        run: composer test
